name: Publish Package

on:
  release:
    types: [published]

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://npm.pkg.github.com/
          scope: "@jim-chien"

      - name: Build Files
        run: |
          yarn
          yarn clean
          yarn build

      - name: Publish NPM Package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_GITHUB_TOKEN}}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        run: gradle build

      - name: Publish Android Package
        run: gradle publish
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{secrets.PUBLISH_GITHUB_TOKEN}}
